version: '3.0'
services:
  bank_api:
    image: node
    container_name: "bank_api"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_STRING='mongodb://bank_db/nosh?authSource=admin'
      - REDIS_HOST=bank_cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispassword
      - REDIS_TTL=10000000
      - ACCESS_TOKEN_SECRET='crazy secret'
      - ACCESS_TOKEN_SECRET_LIFE_SPAN=5
      - REFRESH_TOKEN_SECRET='crazy secret'
      - REFRESH_TOKEN_SECRET_LIFE_SPAN=10
    networks:
      - netty
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - bank_db
      - bank_cache
  
  bank_db:
    image: postgres
    container_name: "bank_db"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: "always"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  bank_cache:
    image: redis:6.2-alpine
    container_name: "bank_cache"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    restart: "always"
    volumes:
      - cache:/data
  
  proxy:
    build:
      context: ./infra
      dockerfile: Dockerfile
    image: nginx
    hostname: nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - bank_api
    networks:
      - netty
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  netty:
    external: true
volumes:
  appCache:
  cache:
    driver: local
  pgdata:  
  