version: '3'

services:

  bank_api:
    build:
      context: .
      dockerfile: Dockerfile # is
    hostname: bank_api
    env_file:
      - docker.env
    ports:
      - "4000:4000" ## add depends_on 

  bank_db:
      image: mongo:latest
      restart: always
      hostname: bank_db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=rootpassword
        - MONGO_INITDB_DATABASE=nosh
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data:db
    
  bank_cache:
    image: redis:latest
    restart: "always"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data

    
  proxy:
    build:
      context: ./infra
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - bank_api
    volumes:
      - nginx_data:/var/cache/


networks:
  default:
volumes:
  cache_data:
  mongo_data:
  nginx_data: